version: 2
jobs:
  build_docker_image:
    docker:
      - image: turbinelabs/gcloud-build:latest # includes docker, git and kubectl
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker:
      #    docker_layer_caching: true
      - run: openrc boot
      - run: docker build -t gcr.io/resplendent-fire-2839/nginx:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1 .
      - run: gcloud docker -- push gcr.io/resplendent-fire-2839/nginx:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
  deploy_to_gcloud:
    docker:
      - image: turbinelabs/gcloud-build:latest
    working_directory: /app
    steps:
      - setup_remote_docker:
      #    docker_layer_caching: true
      - run: openrc boot
      - run: kubectl run hello-server --image gcr.io/resplendent-fire-2839/nginx:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1 --port 80
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker_image:
          filters:
            branches:
              only:
                - master
      - deploy_to_gcloud:
          filters:
            branches:
              only:
                - master
          requires:
            - build_docker_image      
                
