version: 2
jobs:
  build:
    environment:
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
parallelism: 1
# push to Google Container Registry (GCR)
  push-dev-server:
    docker:
      - image: turbinelabs/gcloud-build:0.12.4
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - setup_remote_docker
      - run: openrc boot
      - run: docker build -t <YOUR APP NAME> -f ./Dockerfile.gcloud .
      - run: docker tag <YOUR APP NAME> gcr.io/<GCP PROJECT>/<YOUR APP NAME>:$CIRCLE_SHA1
      - run: gcloud docker -- push gcr.io/<GCP PROJECT>/<YOUR APP NAME>:$CIRCLE_SHA1
# Deploy to GKE
  deploy-dev-server:
    docker:
      - image: turbinelabs/gcloud-build:0.12.4
    steps:
      - checkout
      - run: openrc boot
      - run: chmod +x ./.circleci/deploy_qa.sh   #IN THIS FILE, YOU WILL HAVE YOUR kubectl deploy logic
      - run: ./.circleci/deploy_qa.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - <ADD YOUR BRANCHING TAGS HERE>
              ignore:
                - develop
                - master
  dev_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop
              ignore: /.*/
            tags:
              only: <ADD YOUR BRANCHING TAGS HERE>
      - push-dev-server:
          filters:
            branches:
              only: develop
              ignore: /.*/
            tags:
              only: <ADD YOUR BRANCHING TAGS HERE>
      - deploy-dev-server:
          requires:
            - build
            - push-dev-server
          filters:
            branches:
              only: develop
              ignore: /.*/
            tags:
              only: <ADD YOUR BRANCHING TAGS HERE>
