version: 2

jobs:
  build_docker_image:
    filters:
      branches:
        ignore:
          - /.*-patch-.*/
    docker:
      #- image: docker:17.05.0-ce-git
      - image: turbinelabs/gcloud-build:latest # includes docker, git and kubectl
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=$CIRCLE_BUILD_NUM.nginx
          docker build -t  paulvitic/private:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push paulvitic/private:$TAG
  deploy_to_gcloud: 
    filters:
      branches:
        ignore:
          - /.*-patch-.*/
    docker:
      - image: turbinelabs/gcloud-build:latest # includes docker, git and kubectl
    working_directory: /app
    steps:
      - setup_remote_docker
          docker_layer_caching: true
      - run: openrc boot
      - run: | 
          TAG=$CIRCLE_BUILD_NUM.nginx
          kubectl run hello-server --image paulvitic/private:$TAG --port 80
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker_image:
          filters:
            branches:
              only:
                - master
      - deploy_to_gcloud:
          filters:
            branches:
              only:
                - master
          requires:
            - build_docker_image      
                
