version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=nginx.$CIRCLE_BUILD_NUM
          docker build -t  paulvitic/private:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push paulvitic/private:$TAG
